#!/bin/sh

#copy the entire library into /urs/local/include
#so you the user can just #include <tumbletest>

find src/*.hpp -exec cp {} /usr/local/include \;
cp src/tumbletest /usr/local/include/tumbletest
cp src/string_utils /usr/local/include/string_utils
cp src/vector_utils /usr/local/include/vector_utils

